import com.sbnz.sbnz.domain.Disease;
import com.sbnz.sbnz.domain.Symptoms;
import com.sbnz.sbnz.domain.Diagnosis;
import com.sbnz.sbnz.domain.Ingredient;
import com.sbnz.sbnz.domain.Patient;
import com.sbnz.sbnz.domain.Symptom;
import com.sbnz.sbnz.domain.Medication;

query "Get all patients"
    $p: Patient()
end

query "Get Disease"(Long diseaseId)
    $d: Disease(id == diseaseId)
end

query "Get Symptom"(Long symptomId)
    $s: Symptom(id == symptomId)
end

query "Get Medication"(Long medicationId)
    $m: Medication(id == medicationId)
end

query "Get Ingredient"(Long ingredientId)
    $i: Ingredient(id == ingredientId)
end